# Generated by Django 4.2.2 on 2023-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
