# Generated by Django 4.2.2 on 2023-06-08 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=70, unique=True)),
                ("bio", models.CharField(max_length=200)),
                (
                    "profile_photo",
                    models.ImageField(
                        null=True, upload_to=user.models.profile_picture_file_path
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
