# Generated by Django 4.2.2 on 2023-06-08 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followings",
            field=models.ManyToManyField(
                related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
